version: '3'
services:
  api:
    container_name: nodeapp
    build:
      context: .
    ports:
      - '3000:3000'
    networks:
      - app-network
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - api
    networks:
      - app-network
  mongo:
    container_name: mongo_ifood
    image: mongo
    ports:
      - 27017:27017
    networks:
      - app-network
  redis:
    container_name: redis_ifood
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
