version: '3'
services:
  mongo:
    container_name: mongo_ifood
    image: mongo
    ports:
      - 27017:27017
    networks:
      - app-network
  redis:
    container_name: redis_ifood
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
